// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoJBxqRs3ZEgFOhkXD1_roVjY1Eo0-7Js',
    appId: '1:1054915023678:web:91f1389fe7119449c6126f',
    messagingSenderId: '1054915023678',
    projectId: 'nexsync-58c6f',
    authDomain: 'nexsync-58c6f.firebaseapp.com',
    databaseURL: 'https://nexsync-58c6f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nexsync-58c6f.appspot.com',
    measurementId: 'G-SCYH51Y7G1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA28KPqCsgmdKOvCtUFsUUVVcOhv3Gnsxs',
    appId: '1:1054915023678:android:e7cdd5558dfdc025c6126f',
    messagingSenderId: '1054915023678',
    projectId: 'nexsync-58c6f',
    databaseURL: 'https://nexsync-58c6f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nexsync-58c6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdAXzqxMBLl-4Xv3OO-07uoRolDZ9ftNg',
    appId: '1:1054915023678:ios:384fec74326c1e10c6126f',
    messagingSenderId: '1054915023678',
    projectId: 'nexsync-58c6f',
    databaseURL: 'https://nexsync-58c6f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nexsync-58c6f.appspot.com',
    iosBundleId: 'com.example.nexsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdAXzqxMBLl-4Xv3OO-07uoRolDZ9ftNg',
    appId: '1:1054915023678:ios:0174589035010294c6126f',
    messagingSenderId: '1054915023678',
    projectId: 'nexsync-58c6f',
    databaseURL: 'https://nexsync-58c6f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nexsync-58c6f.appspot.com',
    iosBundleId: 'com.example.nexsync.RunnerTests',
  );
}
